### ISSUE TITLE
Option to show completed tasks

### ISSUE THREAD

**Issue by DylanGuedes** [enotcode/todo-bot#3]
Currently, tasks are just deleted. I think that would be great if tasks could be shown as completed. Example:
```
me: /set_show_completed@todo_bot
me: /list@todo_bot
todo_bot: Tasks:
todo_bot: 1 - [ ] Task 1
todo_bot: 2 - [ ] Task 2
me: /complete 1
todo_bot: Tasks:
todo_bot: 1 - [x] Task 1
todo_bot: 2 - [ ] Task 2
```
The behaviour is far from what is running currently, but it doesn't need to change everything now.

**Comment by enotcode** [comment]
Sorry, I think this function is not needed
